### ISSUE TITLE
Error: Cannot find module 'dachshund-logger'

### ISSUE THREAD

**Issue by AmauryBJ** [sbrinkmann/rc522-rfid#1]
Hello,

First thank you a lot for you module.
I follow all the instruction but I still have this error :+1: 

module.js:340
    throw err;
          ^
Error: Cannot find module 'dachshund-logger'

Do you know where can i find this module ?

thank you.

Amaury

**Comment by sbrinkmann** [comment]
Thanks for the hint. There was a logger library which was only used internally. I removed the require statements and published it to npmjs. The problem should be gone.

**Comment by AmauryBJ** [comment]
Thank you very much ! that was quick !
Now the node is starting well but nothing when I put the rfid tag on the rc522. I checked the cables many times. 
thank you
Amaury

**Comment by sbrinkmann** [comment]
I used this documentation to do the wiring http://geraintw.blogspot.de/2014/01/rfid-and-raspberry-pi.html It also provides a python program to test the connection. Maybe you should try this first. 

There is furthermore an alternative C-Program which does mainly the same as the python app does: http://www.nikolaus-lueneburg.de/2014/06/rfid-rc522-modul-mit-spi-schnittstelle/

**Comment by AmauryBJ** [comment]
Thank you for the quick answer.
I tried with the Python script and it is working well. i get all the information.
But i can't make it work with the little node js script.
The script launch correctly but nothing happend when i put the tag on.
thank you 
Amaury

**Comment by AmauryBJ** [comment]
Everything seems to work well. My bad.
Thanks a lot for your help !
Amaury

**Comment by petrometro** [comment]
Having the same trouble as Amaury - wiring hooked up and python module works fine... ran the simple script in the readme with all modules installed... nothing. The script is clearly running too.

Would like to know what solved your issue Amaury :) Otherwise, any debugging advice ?
Cheers for the module !

**Comment by petrometro** [comment]
i think because the rpi-rc522 lib only supports ultralight cards and i have mifare 1k...
